[pytest]
addopts = -v --strict-markers --tb=short
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
     smoke = Critical tests that run on every commit or pull request
     regression : Full regression test suite
     edge : Edge case and negative tests
     ui: UI automation tests
     api: API automation tests
     db: Database validation tests
     e2e: End-to-end business flow tests

filterwarnings =
     ignore::DeprecationWarning

